[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "biom"
version = "0.0.14"
authors = [
    { name = "Aleksandr Fedorov", email = "aleksandr.fedorov@imm.ox.ac.uk" },
]
description = "Modules for biological data analysis"
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.12"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
[project.optional-dependencies]
repmasker = []
io = [
    "pysam >= 0.21.0, < 1",
]
gindex = [
    "intervaltree >= 3.1.0, < 4",
    "pybedtools >= 0.9.1, < 1",
    "sortedcontainers >= 2.4.0, < 3",
]
ensembl = [
    "pandas >= 2.0.0, < 3",
]
annotation = [
    "biom[io]",
    "biom[gindex]",
]
all = [
    "biom[repmasker]",
    "biom[io]",
    "biom[gindex]",
    "biom[ensembl]",
    "biom[annotation]",
]


[project.urls]
"Homepage" = "https://github.com/alnfedorov/biom"
"Bug Tracker" = "https://github.com/alnfedorov/biom/issues"
