[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "biom"
version = "0.0.8"
authors = [
    { name = "Aleksandr Fedorov", email = "anfedrov@hse.ru" },
]
description = "Modules for biological data analysis"
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "intervaltree ~= 3.1.0",
    "pybedtools ~= 0.9.0",
    "sortedcontainers ~= 2.4.0",
    "pandas ~= 2.0.0",
    "joblib ~= 1.2.0",
    "pysam ~= 0.21.0",
    "scipy ~= 1.10.1",
    "pyBigWig ~= 0.3.22",
    "numba ~= 0.57.0",
    "MACS3 ~= 3.0.0b1"
]

[project.urls]
"Homepage" = "https://github.com/alnfedorov/biom"
"Bug Tracker" = "https://github.com/alnfedorov/biom/issues"
