[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "biom"
version = "0.0.13"
authors = [
    { name = "Aleksandr Fedorov", email = "aleksandr.fedorov@imm.ox.ac.uk" },
]
description = "Modules for biological data analysis"
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
[project.optional-dependencies]
ensembl = [
    "pandas >= 2.0.0, < 3",
]
sam = [
    "pysam >= 0.21.0, < 1",
]
gindex = [
    "intervaltree >= 3.1.0, < 4",
    "pybedtools >= 0.9.1, < 1",
    "sortedcontainers >= 2.4.0, < 3",
]
ripper = [
    "pysam >= 0.21.0, < 1",
    "scipy >= 1.10.1, < 2",
    "pyBigWig >= 0.3.22, < 0.4",
    "numba >= 0.57.0, < 0.60",
    "MACS3 >= 3.0.0b1, < 4",
    "pandas >= 2.0.0, < 3",
    "joblib >= 1.3.0, < 2",
]
all = [
    "biom[ensembl]",
    "biom[gindex]",
    "biom[ripper]",
    "biom[sam]",
]


[project.urls]
"Homepage" = "https://github.com/alnfedorov/biom"
"Bug Tracker" = "https://github.com/alnfedorov/biom/issues"
