[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "biom"
version = "0.0.1"
authors = [
    { name = "Aleksandr Fedorov", email = "anfedrov@hse.ru" },
]
description = "Modules for biological data analysis"
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/alnfedorov/biom"
"Bug Tracker" = "https://github.com/alnfedorov/biom/issues"
